#!/bin/bash


DEV_UNRESTRICTED='eth0'
GW_UNRESTRICTED='10.30.52.1'


DEV_HIGH_SPEED='wlan0'
GW_HIGH_SPEED='10.30.8.1'



# ip route add <network>/<nw bits> via <gateway> dev <interface>

ip route add 31.13.0.0/16 via $GW_UNRESTRICTED dev $DEV_UNRESTRICTED
ip route add 199.16.158.0/24 via $GW_UNRESTRICTED dev $DEV_UNRESTRICTED
ip route add 54.0.0.0/8 via $GW_UNRESTRICTED dev $DEV_UNRESTRICTED
ip route add 216.58.196.110 via $GW_UNRESTRICTED dev $DEV_UNRESTRICTED
ip route add 216.58.220.46 via $GW_UNRESTRICTED dev $DEV_UNRESTRICTED
ip route add 108.174.0.0/16 via $GW_UNRESTRICTED dev $DEV_UNRESTRICTED


ip route del default
ip route add default via $GW_HIGH_SPEED dev $DEV_HIGH_SPEED


